version: '3'
services:
  postgres:
    image: postgres:15.5
    container_name: project-jacked-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5432}:5432
  postgres-test:
    image: postgres:15.5
    container_name: project-jacked-test-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD:-postgres}
    ports:
      - ${DB_TEST_PORT:-5433}:5432
